### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/incident-reports#5]
According to https://team-compass.2i2c.org/projects/managed-hubs/incidents/#create-an-incident-report we now use PagerDuty's post-mortem feature for incidents reports. I think that this repository might create confusion around this practice.

Maybe we should consider archiving this repository or leave a note somewhere visible that this repository is no longer used to avoid confusion.

**Comment by yuvipanda** [comment]
Hmm, i thought this was where we were posting the pdfs from
Pagerduty publicly?

**Comment by GeorgianaElena** [comment]
Well, I guess I was the one that got confused. Indeed, there is a section at the end explaining this. Sorryyyyyyyyy 😬
